### ISSUE TITLE
Make compatible with BrainGlobe Atlas API

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/PyNutil#22]
Currently, atlases are included in the PyNutil package (AMBA CCF and WHS). Atlases could instead be fetched from the BrainGlobe Atlas API. But there are issues regarding atlas orientation that have to be resolved (Nesys tools use atlases in different orientation to the Atlas API). To be discussed.

**Comment by PolarBean** [comment]
This is done, though we still need to have a conversation about orientation consistency between tools.
